version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  static-volume: {}
  media-volume: {}
  react-app-volume: {}

services:
  react: &react
    build:
      context: .
      dockerfile: ./compose/production/react/Dockerfile
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - django
      - postgres
    image: komax_production_frontend
    volumes:
      - react-app-volume:/frontend/build
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.react.loadbalancer.server.port=8080"

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start
    #command: python /app/manage.py runserver 0.0.0.0:9000
    image: komax_production_django
    restart: always
    depends_on:
      - postgres
    volumes:
      - static-volume:/var/komax_site/static
      # - static-volume:/app/static
      - media-volume:/var/komax_site/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "9000:9000"
    labels:
      - "traefik.enable=true"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: komax_production_postgres
    restart: always
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: komax_production_traefik
    restart: always
    depends_on:
      - django
    env_file:
      - ./.envs/.production/.traefik
    volumes:
      - production_traefik:/etc/traefik/acme
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

#  redis:
#    image: redis:3.2
#    restart: always
#    # labels:
#    #   - "traefik.enable=true"
#    ports:
#      - "6379"
#
#  rabbit:
#    image: rabbitmq:3.8-alpine
#    restart: always
#    env_file:
#      - ./.envs/.local/.django
#    ports:
#      - "5672"
#
#  celeryworker:
#    <<: *django
#    image: tiktune_local_celeryworker
#    restart: always
#    depends_on:
#      - redis
#      - rabbit
#      - postgres
#    ports: []
#    command: /start-celeryworker
#
#  flower: &flower
#    <<: *django
#    image: komax_local_flower
#    restart: always
#    ports:
#      - "5555:5555"
#    command: /start-flower

#  nginx: &nginx
#    restart: always
#    build:
#      context: .
#      dockerfile: ./compose/nginx/Dockerfile
#    image: nginx_local
#    # image: nginx:apline
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - static-volume:/www/static
#      - media-volume:/www/media
#      - react-app-volume:/frontend/build
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - django
#      - postgres
#      - react

