# Generated by Django 2.2.7 on 2020-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komaxtask',
            name='type_of_sort',
            field=models.CharField(default='parallel', max_length=128),
            preserve_default=False,
        ),
    ]
