# Generated by Django 2.2.7 on 2020-01-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomaxWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField()),
                ('komax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.Komax')),
                ('komax_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.KomaxTask')),
            ],
        ),
    ]
