# Generated by Django 2.2.7 on 2020-01-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0002_komaxwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
    ]
