# Generated by Django 2.2.7 on 2020-02-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0002_komaxtask_type_of_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komaxtask',
            old_name='type_of_sort',
            new_name='type_of_allocation',
        ),
    ]
