# Generated by Django 2.2.7 on 2020-02-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0003_auto_20200217_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='komaxtask',
            name='kappas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Kappa'),
        ),
        migrations.AddField(
            model_name='taskpersonal',
            name='kappa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Kappa'),
        ),
    ]
