# Generated by Django 2.2.7 on 2020-02-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0003_auto_20200210_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komaxtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
