# Generated by Django 3.0.3 on 2020-05-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0019_auto_20200406_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='komaxtask',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Worker'),
        ),
    ]
