# Generated by Django 3.0 on 2020-05-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0023_auto_20200527_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomaxSeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_name', models.CharField(max_length=64, unique=True)),
                ('seal_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='komaxterminal',
            name='seal_available',
        ),
        migrations.AddField(
            model_name='worker',
            name='current_komax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='komax_app.Komax'),
        ),
        migrations.AddField(
            model_name='worker',
            name='locale',
            field=models.SmallIntegerField(choices=[(1, 'ru'), (2, 'en')], default=1, verbose_name='language'),
        ),
    ]
