# Generated by Django 3.0.7 on 2020-06-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0026_komaxterminal_seal_installed'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomaxTaskCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now=True, verbose_name='Time last updated')),
                ('left_time', models.PositiveIntegerField(verbose_name='Time left to create harness')),
                ('percent_completion', models.PositiveSmallIntegerField(verbose_name='Percent completion harness')),
                ('harness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.Harness')),
                ('komax_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.KomaxTask', unique=True)),
            ],
        ),
    ]
