# Generated by Django 2.2.7 on 2020-02-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komax',
            name='group_of_square',
            field=models.CharField(default='1 2 3', max_length=6),
            preserve_default=False,
        ),
    ]
