# Generated by Django 2.2.7 on 2020-02-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0002_komax_group_of_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kappa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='kappa')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Work'), (2, 'Repair'), (0, 'Not working')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='taskpersonal',
            name='komax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Komax'),
        ),
        migrations.AddField(
            model_name='komaxtask',
            name='kappas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Kappa'),
        ),
        migrations.AddField(
            model_name='taskpersonal',
            name='kappa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Kappa'),
        ),
    ]
