# Generated by Django 2.2.7 on 2020-02-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0003_auto_20200217_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harnesschart',
            name='wire_type',
            field=models.CharField(max_length=256),
        ),
    ]
