# Generated by Django 2.2.7 on 2020-02-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0004_auto_20200217_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harnesschart',
            name='wire_color',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='wire_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='taskpersonal',
            name='wire_color',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='taskpersonal',
            name='wire_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
