# Generated by Django 2.2.7 on 2020-02-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0006_komaxterminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komaxterminal',
            name='terminal_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
