# Generated by Django 2.2.7 on 2020-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0008_auto_20200303_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komaxterminal',
            name='available',
        ),
        migrations.AddField(
            model_name='komaxterminal',
            name='seal_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='komaxterminal',
            name='terminal_available',
            field=models.BooleanField(default=True),
        ),
    ]
