# Generated by Django 2.2.7 on 2020-03-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0009_auto_20200313_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harnesschart',
            name='aplicator_1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='aplicator_2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='armirovka_1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='armirovka_2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='notes',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='tube_len_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='tube_len_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='wire_seal_1',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='wire_seal_2',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='wire_terminal_1',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='harnesschart',
            name='wire_terminal_2',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
