# Generated by Django 2.2.7 on 2020-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0011_auto_20200319_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpersonal',
            name='tube_len_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taskpersonal',
            name='tube_len_2',
            field=models.FloatField(null=True),
        ),
    ]
