# Generated by Django 2.2.7 on 2020-03-29 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('komax_app', '0014_auto_20200323_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedKomaxTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Finished', 'Finished')], default='Pending', max_length=64)),
                ('komax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.KomaxTime')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='komaxtask',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='KomaxTaskPersonal',
        ),
        migrations.AddField(
            model_name='orderedkomaxtask',
            name='komax_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.KomaxTask'),
        ),
        migrations.AddField(
            model_name='orderedkomaxtask',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Worker'),
        ),
    ]
