# Generated by Django 2.2.7 on 2020-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0015_auto_20200329_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komaxtask',
            name='ordered',
        ),
        migrations.AddField(
            model_name='komaxtask',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Ordered'), (3, 'Loaded'), (4, 'Done')], default=1),
        ),
    ]
