# Generated by Django 2.2.7 on 2020-04-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0016_auto_20200330_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, upload_to='worker_images/'),
        ),
    ]
