# Generated by Django 3.0 on 2020-05-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0021_remove_komaxtask_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpersonal',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_personal', to='komax_app.Worker'),
        ),
    ]
