# Generated by Django 3.0 on 2020-05-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0022_auto_20200526_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komaxstatus',
            name='komax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.Komax', unique=True),
        ),
    ]
