# Generated by Django 2.2 on 2020-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0025_auto_20200602_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='komaxterminal',
            name='seal_installed',
            field=models.BooleanField(default=True),
        ),
    ]
