# Generated by Django 3.0.7 on 2020-06-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komax_app', '0027_komaxtaskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komax',
            name='identifier',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='komaxtaskcompletion',
            name='harness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='komax_app.Harness'),
        ),
        migrations.AlterField(
            model_name='komaxtaskcompletion',
            name='komax_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komax_app.KomaxTask'),
        ),
    ]
