#!/bin/sh

set -o errexit
# set -o pipefail
set -o nounset


python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput
gunicorn komax_site.wsgi --bind 0.0.0.0:9000 --chdir=/app
