debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.http.tls]

[providers.docker]
defaultRule = "Host(`docker.localhost`)"
endpoint = "unix:///var/run/docker.sock"
# useBindPortIP = true
# domain = "komax.prettl.ru"
watch = true
exposedByDefault = false
# network = "web"

#[file]
#filename = "/etc/traefik/dynamic-conf.toml"

[api]
  insecure = true
  dashboard = true

#[log]
#  level = "DEBUG"

#[accessLog]
#  bufferingSize = 0

[certificatesresolvers.default.acme]
  email = "polyakgerman@gmail.com"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesresolvers.default.acme.httpChallenge]
    entryPoint = "http"
